export type THeaderList = {
    id:number
    named:string
    link:string
}
export const HeaderList: THeaderList[] = [
    {
        id:1,
        named:'Home',
        link:'/'
    },
    {
        id:2,
        named:'Posts',
        link:'/posts'
    },
    {
        id:3,
        named:'Sign-in',
        link:'/sign-in'
    },
    {
        id:4,
        named:'Sign-out',
        link:'/sign-out'
    },  
    {
        id:5,
        named:'Account',
        link:``
    }, 
]